# Generated by Django 6.1 on 2026-08-24 14:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('capacity', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'marketplace_sessions',
                'ordering': ['start_time'],
                'indexes': [models.Index(fields=['start_time'], name='session_start_time_idx'), models.Index(fields=['creator', 'start_time'], name='session_creator_time_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('capacity__gt', 0)), name='session_positive_capacity'), models.CheckConstraint(condition=models.Q(('end_time__gt', models.F('start_time'))), name='session_end_after_start')],
            },
        ),
    ]
